// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperheroBattle.DataAccessHandlers;

namespace SuperheroBattle.Client.Api.Migrations
{
    [DbContext(typeof(SuperheroBattleContext))]
    [Migration("20190522121403_AddAbilityLevelMigration")]
    partial class AddAbilityLevelMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SuperheroBattle.Core.Entities.Ability", b =>
                {
                    b.Property<int>("AbilityID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("StrengthLevel");

                    b.HasKey("AbilityID");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("SuperheroBattle.Core.Entities.Superhero", b =>
                {
                    b.Property<int>("SuperheroID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AbilityModifier");

                    b.Property<int?>("AgeAtOrigin");

                    b.Property<bool>("IsAlien");

                    b.Property<string>("OriginStory");

                    b.Property<int?>("PlanetOfOrigin");

                    b.Property<string>("SecretIdentity");

                    b.Property<string>("SuperheroName")
                        .IsRequired();

                    b.Property<int>("Universe");

                    b.Property<int>("YearOfAppearance");

                    b.HasKey("SuperheroID");

                    b.ToTable("Superheroes");
                });

            modelBuilder.Entity("SuperheroBattle.Core.Entities.SuperheroAbility", b =>
                {
                    b.Property<int>("SuperheroID");

                    b.Property<int>("AbilityID");

                    b.HasKey("SuperheroID", "AbilityID");

                    b.HasIndex("AbilityID");

                    b.ToTable("SuperheroAbilities");
                });

            modelBuilder.Entity("SuperheroBattle.Core.Entities.SuperheroAbility", b =>
                {
                    b.HasOne("SuperheroBattle.Core.Entities.Ability", "Ability")
                        .WithMany("SuperheroAbilities")
                        .HasForeignKey("AbilityID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SuperheroBattle.Core.Entities.Superhero", "Superhero")
                        .WithMany("SuperheroAbilities")
                        .HasForeignKey("SuperheroID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
